# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.




# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: F# for Fun and Profit
description: "This site shows you ways that F# can help in day-to-day development of mainstream commercial business software"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fsharpforfunandprofit.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ScottWlaschin
github_username:  swlaschin

# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
collections:
  posts:
    output:   true

# Reading & Writing
encoding: "utf-8"
exclude:
  - Gemfile
  - Gemfile.lock
  - .git/
include:   [".htaccess"]
keep_files: [".git", ".svn"]
    
# Build settings
markdown: kramdown
theme: minima
highlighter: rouge

#permalink: /:month-:day-:year/:title.html
permalink: /posts/:title/

# Plugins
whitelist: []
plugins:   []

# Serve settings  
port: 4000
host: localhost

# command line
#  jekyll build --verbose > jekyll.log
#  jekyll serve --no-watch --skip-initial-build

category_dir: category

# Markdown Processor
kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  parse_block_html: false  # turn on locally as needed