title: Imagio blog
description: "Just blog"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://imagio.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
collections:
  posts:
    output:   true

# Reading & Writing
encoding: "utf-8"
exclude:
  - Gemfile
  - Gemfile.lock
  - .git/
include:   [".htaccess"]
keep_files: [".git", ".svn"]
    
# Build settings
markdown: kramdown
theme: minima
highlighter: rouge

#permalink: /:month-:day-:year/:title.html
permalink: /posts/:title/

# Plugins
whitelist: []
plugins:   []

# Serve settings  
port: 4000
host: localhost

# command line
#  jekyll build --verbose > jekyll.log
#  jekyll serve --no-watch --skip-initial-build

category_dir: category

# Markdown Processor
kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  parse_block_html: false  # turn on locally as needed